spring:
  application:
    name: ${APPLICATION_NAME:AI-CHARGE-BATCH}
  datasource:
    #url: "soksok-aurora-db-serverless.cluster-ctuthbmrxl9o.ap-northeast-2.rds.amazonaws.com"
    #      url: jdbc:mysql:aurora://<cluster endpoint where the writer instance is located>:<port>/<database name>?<optional parameters>
    #url: "jdbc:mysql://127.0.0.1:3306/soksok"
    url: "jdbc:mysql://soksok-aurora-db-serverless.cluster-ctuthbmrxl9o.ap-northeast-2.rds.amazonaws.com:3306/soksok"
    username: "soksok"
    password: "handle5565!!"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    #      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    #spring.jpa.hibernate.naming.physical-strategy = org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
#        show_sql: true
        format_sql: true
